name: Publish

on: push

jobs:
  publish:
    name: Publish reveal.js slides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: sudo apt update -qy && sudo apt install ffmpeg -qy
      - run: jupyter nbconvert *.ipynb --to slides --execute
      - run: mkdir dist && mv *.slides.html dist/index.html
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
